
spring:
  masterdatasource:
    url: jdbc:mysql://127.0.0.1:3311/cbvac
    username: root
    password: fNty2u8awl
    platform: mysql
  slavedatasource:
    url: jdbc:mysql://127.0.0.1:3311/cbvac
    username: root
    password: fNty2u8awl
    platform: mysql
  application:
    name: CbvacWebApplication


