
spring:
  masterdatasource:
    url: jdbc:mysql://127.0.0.1:3306/cbv_dev
    username: root
    password: fNty2u8awl
    platform: mysql
  slavedatasource:
    url: jdbc:mysql://127.0.0.1:3306/cbv_dev
    username: root
    password: fNty2u8awl
    platform: mysql
  application:
    name: CbvacWebApplication
